"""add agent id to submission

Revision ID: 01cfca842715
Revises: 978362826bf7
Create Date: 2026-03-15 00:02:30.816741

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "01cfca842715"
down_revision: str | None = "978362826bf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("agent_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_submissions_agent_id"), "submissions", ["agent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_agent_id"), table_name="submissions")
    op.drop_column("submissions", "agent_id")
    # ### end Alembic commands ###
