"""add logs to agent containers

Revision ID: 0e4b8796ced2
Revises: 1597ec254317
Create Date: 2026-04-10 18:29:35.806613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e4b8796ced2'
down_revision: Union[str, None] = '1597ec254317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_containers', sa.Column('logs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_containers', 'logs')
    # ### end Alembic commands ###
