"""agent containers

Revision ID: 1597ec254317
Revises: b7a1c9e4d2f0
Create Date: 2026-04-10 17:48:54.524390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1597ec254317'
down_revision: Union[str, None] = 'b7a1c9e4d2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_containers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uptime_seconds', sa.Float(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_containers_agent_id'), 'agent_containers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_containers_container_id'), 'agent_containers', ['container_id'], unique=True)
    op.create_index(op.f('ix_agent_containers_id'), 'agent_containers', ['id'], unique=False)
    op.create_index(op.f('ix_agent_containers_match_id'), 'agent_containers', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_containers_match_id'), table_name='agent_containers')
    op.drop_index(op.f('ix_agent_containers_id'), table_name='agent_containers')
    op.drop_index(op.f('ix_agent_containers_container_id'), table_name='agent_containers')
    op.drop_index(op.f('ix_agent_containers_agent_id'), table_name='agent_containers')
    op.drop_table('agent_containers')
    # ### end Alembic commands ###
