"""add_profile_picture_url

Revision ID: 4c94a97de484
Revises: d093208e4420
Create Date: 2025-12-21 02:51:07.052457

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4c94a97de484"
down_revision: str | None = "aa252e285444"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_picture_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_picture_url")
    # ### end Alembic commands ###
