"""Move state from submission to build_job

Revision ID: 978362826bf7
Revises: f4b5244cbe9a
Create Date: 2026-03-05 14:06:36.845483

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "978362826bf7"
down_revision: str | None = "f4b5244cbe9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "build_jobs", "submissions", ["submission_id"], ["id"])
    op.drop_column("submissions", "status")
    op.drop_column("submissions", "image_tag")
    op.drop_column("submissions", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("image_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("submissions", sa.Column("image_tag", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "submissions",
        sa.Column(
            "status",
            postgresql.ENUM("QUEUED", "BUILDING", "COMPLETED", "FAILED", name="submissionstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "build_jobs", type_="foreignkey")
    # ### end Alembic commands ###
