"""Add game_state to matches

Revision ID: af42d14dff92
Revises: 978362826bf7
Create Date: 2026-03-15 14:24:38.978908

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "af42d14dff92"
down_revision: str | None = "978362826bf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("game_state", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "game_state")
    # ### end Alembic commands ###
