"""rework agent stats

Revision ID: b1cb92f7e0ab
Revises: b77f8cc711b2
Create Date: 2026-05-16 14:11:26.367987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b1cb92f7e0ab"
down_revision: str | None = "b77f8cc711b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("wins", sa.Integer(), nullable=False))
    op.add_column("agents", sa.Column("losses", sa.Integer(), nullable=False))
    op.add_column("agents", sa.Column("draws", sa.Integer(), nullable=False))
    op.add_column("agents", sa.Column("matches_played", sa.Integer(), nullable=False))
    op.add_column("agents", sa.Column("elo", sa.Integer(), nullable=True))
    op.drop_column("agents", "stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents", sa.Column("stats", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False)
    )
    op.drop_column("agents", "elo")
    op.drop_column("agents", "matches_played")
    op.drop_column("agents", "draws")
    op.drop_column("agents", "losses")
    op.drop_column("agents", "wins")
    # ### end Alembic commands ###
