"""image cleanup and create flags

Revision ID: b3a3db84af20
Revises: 3851068f20dc
Create Date: 2026-06-06 16:22:55.058175

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b3a3db84af20"
down_revision: str | None = "3851068f20dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build_jobs",
        sa.Column(
            "cleanup_image",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
    )
    op.add_column(
        "match_jobs",
        sa.Column(
            "create_images",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_jobs", "create_images")
    op.drop_column("build_jobs", "cleanup_image")
    # ### end Alembic commands ###
