"""image cleanup and create flags

Revision ID: b3a3db84af20
Revises: 3851068f20dc
Create Date: 2026-06-06 16:22:55.058175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3a3db84af20'
down_revision: Union[str, None] = '3851068f20dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_jobs', sa.Column('cleanup_image', sa.Boolean(), nullable=False))
    op.add_column('match_jobs', sa.Column('create_images', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_jobs', 'create_images')
    op.drop_column('build_jobs', 'cleanup_image')
    # ### end Alembic commands ###
