"""add_email_verification_and_password_reset_tokens

Revision ID: d093208e4420
Revises: 6bd0852dfd26
Create Date: 2025-11-02 14:44:41.271468

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d093208e4420"
down_revision: str | None = "6bd0852dfd26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("email_verification_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("users", sa.Column("email_verification_expires_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("password_reset_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("users", sa.Column("password_reset_expires_at", sa.DateTime(), nullable=True))
    op.create_index("ix_email_verification_expires_at", "users", ["email_verification_expires_at"], unique=False)
    op.create_index("ix_password_reset_expires_at", "users", ["password_reset_expires_at"], unique=False)
    op.create_index(
        op.f("ix_users_email_verification_token_hash"), "users", ["email_verification_token_hash"], unique=False
    )
    op.create_index(op.f("ix_users_email_verified"), "users", ["email_verified"], unique=False)
    op.create_index(op.f("ix_users_password_reset_token_hash"), "users", ["password_reset_token_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password_reset_token_hash"), table_name="users")
    op.drop_index(op.f("ix_users_email_verified"), table_name="users")
    op.drop_index(op.f("ix_users_email_verification_token_hash"), table_name="users")
    op.drop_index("ix_password_reset_expires_at", table_name="users")
    op.drop_index("ix_email_verification_expires_at", table_name="users")
    op.drop_column("users", "password_reset_expires_at")
    op.drop_column("users", "password_reset_token_hash")
    op.drop_column("users", "email_verification_expires_at")
    op.drop_column("users", "email_verification_token_hash")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
