"""Add client_error to MatchStatus

Revision ID: ec3ce9a59142
Revises: af42d14dff92
Create Date: 2026-03-20 22:48:36.214657

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ec3ce9a59142"
down_revision: str | None = "af42d14dff92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE matchstatus ADD VALUE 'CLIENT_ERROR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
