"""allow active submission nullable

Revision ID: ef450c3b7b81
Revises: 01cfca842715
Create Date: 2026-03-15 00:18:07.125886

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ef450c3b7b81"
down_revision: str | None = "01cfca842715"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("agents", "active_submission_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("agents", "active_submission_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
