"""add agents and jobs

Revision ID: f4b5244cbe9a
Revises: 4c94a97de484
Create Date: 2026-03-02 23:39:09.128494

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f4b5244cbe9a"
down_revision: str | None = "4c94a97de484"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create enum types manually for PostgreSQL
    bind = op.get_bind()

    # Check for jobstatus
    has_jobstatus = bind.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'jobstatus')")).scalar()
    if not has_jobstatus:
        job_status = sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="jobstatus")
        job_status.create(bind)

    # Check for gametype
    has_gametype = bind.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gametype')")).scalar()
    if not has_gametype:
        game_type = sa.Enum("TICTACTOE", "CHESS", "CONNECT_FOUR", name="gametype")
        game_type.create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("agents",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("active_submission_id", sa.Uuid(), nullable=False),
    sa.Column("stats", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.create_index(op.f("ix_agents_user_id"), "agents", ["user_id"], unique=False)
    op.create_table("build_jobs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("submission_id", sa.Uuid(), nullable=False),
    sa.Column("status", postgresql.ENUM("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="jobstatus",
        create_type=False), nullable=False),
    sa.Column("logs", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("image_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("image_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_build_jobs_id"), "build_jobs", ["id"], unique=False)
    op.create_index(op.f("ix_build_jobs_submission_id"), "build_jobs", ["submission_id"], unique=False)
    op.create_table("match_jobs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("match_id", sa.Uuid(), nullable=False),
    sa.Column("status", postgresql.ENUM("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="jobstatus",
        create_type=False), nullable=False),
    sa.Column("logs", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("result", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_match_jobs_id"), "match_jobs", ["id"], unique=False)
    op.create_index(op.f("ix_match_jobs_match_id"), "match_jobs", ["match_id"], unique=False)
    op.add_column("matches", sa.Column("game_type", postgresql.ENUM("TICTACTOE", "CHESS", "CONNECT_FOUR",
        name="gametype", create_type=False), nullable=False))
    op.add_column("matches", sa.Column("agent_ids", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_matches_game_type"), "matches", ["game_type"], unique=False)
    op.drop_column("matches", "logs")
    op.drop_column("submissions", "logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submissions", sa.Column("logs", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("matches", sa.Column("logs", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_matches_game_type"), table_name="matches")
    op.drop_column("matches", "agent_ids")
    op.drop_column("matches", "game_type")
    op.drop_index(op.f("ix_match_jobs_match_id"), table_name="match_jobs")
    op.drop_index(op.f("ix_match_jobs_id"), table_name="match_jobs")
    op.drop_table("match_jobs")
    op.drop_index(op.f("ix_build_jobs_submission_id"), table_name="build_jobs")
    op.drop_index(op.f("ix_build_jobs_id"), table_name="build_jobs")
    op.drop_table("build_jobs")
    op.drop_index(op.f("ix_agents_user_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###

    # Drop enum types manually
    sa.Enum(name="gametype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
